### ISSUE TITLE
when working with minimal UI card hands list doesn't overlay correctly

### ISSUE THREAD

**Issue by joeschnurr** [kristianserrano/card-hands-list#4]
If you have `Minimal UI` enabled you must set Player list to `standard `and `always`.  If you leave it compressed ( the default when loaded ) the card list is squashed.

However if you set the player list to standard and always show the player list and the card hand list overlay in the same space vs being stacked on one another.

![Screenshot_20230806_120643](https://github.com/kristianserrano/card-hands-list/assets/2029050/dbf166a3-e675-407d-abac-66b8ce8108be)

From talking with Kristian:

> He's dynamically applying some inline styles to toggle the display, but he's also adding absolute positioning to the player list
> I can try to detect the installation of the module and add a class that accommodates the display, but I worry I'll also have to duplicate some of his scripting to simulate the behavior

**Comment by kristianserrano** [comment]
@joeschnurr I think this is going to require a solution from the Minimal UI side. I've submitted an issue there, and linked back to this issue.

**Comment by joeschnurr** [comment]
@kristianserrano - no worries.  thanks for taking a look!

**Comment by kristianserrano** [comment]
Fixed in v1.8.2
