### ISSUE TITLE
Card Images too large after update, hands list pushes toolbar and and player list out of view

### ISSUE THREAD

**Issue by Sephalopod** [kristianserrano/card-hands-list#5]
I updated to v1.8.4 and the card images in the Card Hands list are about 8 times bigger than before, causing the list to take up the the whole toolbar and player list area. I also can't click the button to collapse the list. It persists with all other mods disabled. I'm using DnD 5e v2.3.1 and Foundry v11.309, on Microsoft Edge v119.0.2151.44.

**Comment by kristianserrano** [comment]
I can't duplicate this on Foundry v11.314. Try updating Foundry and see if that's the issue.

Keep in mind that Foundry v11.309 and v11.313 issued security updates for Electron which requires the app to be uninstalled and reinstalled.

I think older versions of Electron might not offer browser support for some CSS features I'm using such as `is()` or `has()` in the CSS selectors. If this ends up being the case, I'll change the minimum compatibility of the module to a specific version of Foundry v11.

**Comment by kristianserrano** [comment]
I just installed FVTT v11.309, and it seems to be working fine there. Maybe there's a caching issue? Restarting your server and/or uninstalling/reinstalling the module might fix it.

**Comment by kristianserrano** [comment]
I just realized you said you were using Edge as the browser. I have the same version, but I'm still unable to reproduce the bug. Definitely try restarting your server and/or uninstall/reinstall the module.

**Comment by Sephalopod** [comment]
I didn't think to try those fixes one at a time until just now, but after clearing my cache, restarting the server, and reinstalling the module it is back to normal! Sorry I can't specify which fix worked. Thank you for looking into it and for the advice!

**Comment by kristianserrano** [comment]
No worries at all. I'm just glad it's working correctly again. Happy gaming!
