### ISSUE TITLE
Error in the console.

### ISSUE THREAD

**Issue by mrcomac** [kristianserrano/card-hands-list#6]
Foundry: 11.315
SWADE: 3.4.1
Card Hands List: 1.12.4

I'm getting the error below:

```
TypeError: Cannot read properties of undefined (reading 'includes')
    at CardHandsList.getData (CardHandsList.mjs:60:41)
    at CardHandsList._render (CardHandsList.mjs:98:33)
```

Due to this error, i can't use the quick access to see the cards.

**Comment by kristianserrano** [comment]
Ha! I literally caught that same error. There's a 1.12.5 update available that fixes this.
